// Command spike-xbrl is a Phase 1 throwaway spike that parses an IDX XBRL
// instance document (instance.xbrl from the per-issuer instance.zip) and
// prints key financial accounts.
//
// Usage:
//
//	go run ./cmd/spike-xbrl [path/to/instance.xbrl]
//
// Defaults to data/bbca/instance.xbrl.
//
// Findings this spike encodes:
//   - IDX XBRL uses the idx-cor (core accounts) and idx-dei (document/entity
//     info) namespaces, taxonomy version 2020-01-01, generated by Fujitsu
//     Interstage XWand.
//   - Facts reference contexts like CurrentYearInstant (balance sheet date),
//     PriorEndYearInstant, CurrentYearDuration (P&L period), PriorYearDuration.
//   - Monetary facts carry unitRef="IDR" and decimals="-6" (values are full
//     rupiah, reported to millions precision).
package main

import (
	"encoding/xml"
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	nsXBRLI = "http://www.xbrl.org/2003/instance"
	nsCor   = "http://www.idx.co.id/xbrl/taxonomy/2020-01-01/cor"
	nsDei   = "http://www.idx.co.id/xbrl/taxonomy/2020-01-01/dei"
)

// keyAccounts are the idx-cor concepts we want to extract. Present in BBCA
// (bank, Q1 2026). TODO(verify): confirm the same concepts exist for
// non-financial issuers (e.g. TLKM, ASII) — banks use statement 4220000
// while general corporates likely report Revenue/GrossProfit variants.
var keyAccounts = []string{
	"Assets",
	"Liabilities",
	"Equity",
	"EquityAttributableToEquityOwnersOfParentEntity",
	"InterestIncome",
	"ProfitLoss",
	"ProfitLossAttributableToParentEntity",
	"ComprehensiveIncome",
	"CashAndCashEquivalents",
	"BasicEarningsLossPerShareFromContinuingOperations",
}

// deiFields are entity/document metadata concepts from idx-dei.
var deiFields = []string{
	"EntityName",
	"EntityCode",
	"EntityMainIndustry",
	"PeriodOfFinancialStatementsSubmissions",
	"CurrentPeriodEndDate",
}

type context struct {
	id      string
	instant string // set for balance-sheet contexts
	start   string // set for duration contexts
	end     string
	dims    int // number of dimension members; 0 = the "plain" consolidated context
}

func (c context) period() string {
	if c.instant != "" {
		return "as of " + c.instant
	}
	return c.start + " .. " + c.end
}

type fact struct {
	concept    string
	contextRef string
	unitRef    string
	value      string
}

func main() {
	path := "data/bbca/instance.xbrl"
	if len(os.Args) > 1 {
		path = os.Args[1]
	}

	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open instance: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	contexts, facts, err := parse(f)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse: %v\n", err)
		os.Exit(1)
	}

	report(contexts, facts)
}

// parse streams the XBRL instance, collecting contexts and the facts whose
// concept name is in keyAccounts/deiFields. Streaming keeps memory flat even
// though instances are ~2 MB with thousands of dimensional facts.
func parse(r io.Reader) (map[string]context, []fact, error) {
	wantCor := make(map[string]bool, len(keyAccounts))
	for _, a := range keyAccounts {
		wantCor[a] = true
	}
	wantDei := make(map[string]bool, len(deiFields))
	for _, d := range deiFields {
		wantDei[d] = true
	}

	contexts := map[string]context{}
	var facts []fact

	dec := xml.NewDecoder(r)
	for {
		tok, err := dec.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, nil, err
		}
		se, ok := tok.(xml.StartElement)
		if !ok {
			continue
		}

		switch {
		case se.Name.Space == nsXBRLI && se.Name.Local == "context":
			ctx, err := parseContext(dec, se)
			if err != nil {
				return nil, nil, fmt.Errorf("context: %w", err)
			}
			contexts[ctx.id] = ctx

		case (se.Name.Space == nsCor && wantCor[se.Name.Local]) ||
			(se.Name.Space == nsDei && wantDei[se.Name.Local]):
			fa := fact{concept: se.Name.Local}
			for _, a := range se.Attr {
				switch a.Name.Local {
				case "contextRef":
					fa.contextRef = a.Value
				case "unitRef":
					fa.unitRef = a.Value
				}
			}
			var text strings.Builder
			if err := collectText(dec, se.Name, &text); err != nil {
				return nil, nil, fmt.Errorf("fact %s: %w", se.Name.Local, err)
			}
			fa.value = strings.TrimSpace(text.String())
			facts = append(facts, fa)
		}
	}
	return contexts, facts, nil
}

// parseContext consumes a <context> element and extracts id, period, and
// whether it carries dimensional scenario members.
func parseContext(dec *xml.Decoder, start xml.StartElement) (context, error) {
	var ctx context
	for _, a := range start.Attr {
		if a.Name.Local == "id" {
			ctx.id = a.Value
		}
	}
	depth := 1
	var current string
	for depth > 0 {
		tok, err := dec.Token()
		if err != nil {
			return ctx, err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			depth++
			current = t.Name.Local
			if t.Name.Local == "explicitMember" || t.Name.Local == "typedMember" {
				ctx.dims++
			}
		case xml.EndElement:
			depth--
			current = ""
		case xml.CharData:
			s := strings.TrimSpace(string(t))
			if s == "" {
				continue
			}
			switch current {
			case "instant":
				ctx.instant = s
			case "startDate":
				ctx.start = s
			case "endDate":
				ctx.end = s
			}
		}
	}
	return ctx, nil
}

// collectText consumes tokens until the matching end element, appending
// character data. Fact elements are leaf nodes but text blocks can nest markup.
func collectText(dec *xml.Decoder, name xml.Name, sb *strings.Builder) error {
	depth := 1
	for depth > 0 {
		tok, err := dec.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			depth++
		case xml.EndElement:
			depth--
		case xml.CharData:
			sb.Write(t)
		}
	}
	return nil
}

func report(contexts map[string]context, facts []fact) {
	// DEI metadata first.
	fmt.Println("== Entity ==")
	for _, d := range deiFields {
		for _, fa := range facts {
			if fa.concept == d {
				fmt.Printf("  %-42s %s\n", d, fa.value)
				break
			}
		}
	}

	// Key accounts: only plain (non-dimensional) contexts, so we get the
	// consolidated headline number, not per-segment breakdowns.
	fmt.Println("\n== Key accounts (consolidated, IDR) ==")
	order := map[string]int{}
	for i, a := range keyAccounts {
		order[a] = i
	}
	var rows []fact
	for _, fa := range facts {
		ctx, ok := contexts[fa.contextRef]
		if !ok || ctx.dims > 0 {
			continue
		}
		if _, isKey := order[fa.concept]; isKey {
			rows = append(rows, fa)
		}
	}
	sort.SliceStable(rows, func(i, j int) bool {
		if order[rows[i].concept] != order[rows[j].concept] {
			return order[rows[i].concept] < order[rows[j].concept]
		}
		return rows[i].contextRef < rows[j].contextRef
	})
	for _, fa := range rows {
		ctx := contexts[fa.contextRef]
		fmt.Printf("  %-48s %-24s %20s  (%s)\n",
			fa.concept, fa.contextRef, formatIDR(fa.value), ctx.period())
	}
}

// formatIDR adds thousands separators to integer rupiah values; non-numeric
// values (e.g. EPS decimals) pass through unchanged.
func formatIDR(v string) string {
	n, err := strconv.ParseInt(v, 10, 64)
	if err != nil {
		return v
	}
	s := strconv.FormatInt(n, 10)
	neg := strings.HasPrefix(s, "-")
	s = strings.TrimPrefix(s, "-")
	var parts []string
	for len(s) > 3 {
		parts = append([]string{s[len(s)-3:]}, parts...)
		s = s[:len(s)-3]
	}
	parts = append([]string{s}, parts...)
	out := strings.Join(parts, ",")
	if neg {
		out = "-" + out
	}
	return out
}
