// Package xbrl parses IDX financial-report XBRL instance documents.
//
// Phase 1 spike findings encoded here:
//   - IDX instances are generated by Fujitsu Interstage XWand and are highly
//     uniform across issuers. Concepts live in the idx-cor namespace, entity
//     metadata in idx-dei, taxonomy version 2020-01-01.
//   - Facts reference named contexts: CurrentYearInstant (balance-sheet date),
//     PriorEndYearInstant, CurrentYearDuration (P&L period), PriorYearDuration.
//   - Monetary facts carry unitRef="IDR" as full rupiah (decimals="-6").
//   - Dimensional contexts (segment / equity-component breakdowns) carry an
//     xbrldi member and MUST be filtered out to get consolidated headline
//     numbers.
package xbrl

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"io"
	"strconv"
	"strings"
)

const (
	nsXBRLI = "http://www.xbrl.org/2003/instance"
	nsCor   = "http://www.idx.co.id/xbrl/taxonomy/2020-01-01/cor"
	nsDei   = "http://www.idx.co.id/xbrl/taxonomy/2020-01-01/dei"
)

// KeyAccounts are the idx-cor concepts extracted for the financial-report tool.
// Availability varies by industry (e.g. banks expose InterestIncome; general
// corporates expose Revenue). Missing concepts are simply omitted from output.
//
// TODO(verify): confirm concept coverage across non-financial issuers
// (e.g. TLKM, ASII) — only BBCA (a bank) was validated in Phase 1.
var KeyAccounts = []string{
	"Assets",
	"Liabilities",
	"Equity",
	"EquityAttributableToEquityOwnersOfParentEntity",
	"Revenue",
	"GrossProfit",
	"InterestIncome",
	"ProfitLoss",
	"ProfitLossAttributableToParentEntity",
	"ComprehensiveIncome",
	"BasicEarningsLossPerShareFromContinuingOperations",
}

// deiFields are entity/document metadata concepts (idx-dei namespace).
var deiFields = []string{
	"EntityName",
	"EntityCode",
	"EntityMainIndustry",
	"PeriodOfFinancialStatementsSubmissions",
	"CurrentPeriodEndDate",
}

// Report is the parsed, filtered result of one XBRL instance.
type Report struct {
	Entity   Entity    `json:"entity"`
	Accounts []Account `json:"accounts"`
}

// Entity holds document/entity metadata from idx-dei.
type Entity struct {
	Name          string `json:"name"`
	Code          string `json:"code"`
	Industry      string `json:"industry"`
	Period        string `json:"period"`
	PeriodEndDate string `json:"period_end_date"`
}

// Account is a single consolidated financial fact.
type Account struct {
	Concept    string `json:"concept"`
	Context    string `json:"context"`     // e.g. CurrentYearInstant
	Period     string `json:"period"`      // human-readable period
	Value      string `json:"value"`       // raw fact value
	NumericIDR *int64 `json:"numeric_idr"` // parsed integer rupiah, nil if non-numeric
}

type context struct {
	id      string
	instant string
	start   string
	end     string
	dims    int
}

func (c context) period() string {
	if c.instant != "" {
		return "as of " + c.instant
	}
	return c.start + " .. " + c.end
}

type fact struct {
	concept    string
	contextRef string
	value      string
}

// Parse reads an XBRL instance document and returns the consolidated key
// accounts plus entity metadata.
func Parse(r io.Reader) (*Report, error) {
	wantCor := toSet(KeyAccounts)
	wantDei := toSet(deiFields)

	contexts := map[string]context{}
	var facts []fact

	dec := xml.NewDecoder(r)
	for {
		tok, err := dec.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("read token: %w", err)
		}
		se, ok := tok.(xml.StartElement)
		if !ok {
			continue
		}
		switch {
		case se.Name.Space == nsXBRLI && se.Name.Local == "context":
			ctx, err := parseContext(dec, se)
			if err != nil {
				return nil, fmt.Errorf("parse context: %w", err)
			}
			contexts[ctx.id] = ctx
		case (se.Name.Space == nsCor && wantCor[se.Name.Local]) ||
			(se.Name.Space == nsDei && wantDei[se.Name.Local]):
			fa := fact{concept: se.Name.Local}
			for _, a := range se.Attr {
				if a.Name.Local == "contextRef" {
					fa.contextRef = a.Value
				}
			}
			var sb strings.Builder
			if err := collectText(dec, &sb); err != nil {
				return nil, fmt.Errorf("read fact %s: %w", se.Name.Local, err)
			}
			fa.value = strings.TrimSpace(sb.String())
			facts = append(facts, fa)
		}
	}

	return build(contexts, facts), nil
}

// ParseBytes is a convenience wrapper around Parse.
func ParseBytes(b []byte) (*Report, error) { return Parse(bytes.NewReader(b)) }

func build(contexts map[string]context, facts []fact) *Report {
	rep := &Report{}

	dei := map[string]string{}
	for _, fa := range facts {
		if _, ok := contexts[fa.contextRef]; !ok {
			// dei facts also use CurrentYearInstant; keep first non-empty.
		}
		if _, isDei := deiSet[fa.concept]; isDei {
			if dei[fa.concept] == "" {
				dei[fa.concept] = fa.value
			}
		}
	}
	rep.Entity = Entity{
		Name:          dei["EntityName"],
		Code:          dei["EntityCode"],
		Industry:      dei["EntityMainIndustry"],
		Period:        dei["PeriodOfFinancialStatementsSubmissions"],
		PeriodEndDate: dei["CurrentPeriodEndDate"],
	}

	order := map[string]int{}
	for i, a := range KeyAccounts {
		order[a] = i
	}
	for _, fa := range facts {
		ctx, ok := contexts[fa.contextRef]
		if !ok || ctx.dims > 0 { // skip dimensional breakdowns
			continue
		}
		if _, isKey := order[fa.concept]; !isKey {
			continue
		}
		acc := Account{
			Concept: fa.concept,
			Context: fa.contextRef,
			Period:  ctx.period(),
			Value:   fa.value,
		}
		if n, err := strconv.ParseInt(fa.value, 10, 64); err == nil {
			acc.NumericIDR = &n
		}
		rep.Accounts = append(rep.Accounts, acc)
	}
	sortAccounts(rep.Accounts, order)
	return rep
}

func parseContext(dec *xml.Decoder, start xml.StartElement) (context, error) {
	var ctx context
	for _, a := range start.Attr {
		if a.Name.Local == "id" {
			ctx.id = a.Value
		}
	}
	depth := 1
	var current string
	for depth > 0 {
		tok, err := dec.Token()
		if err != nil {
			return ctx, err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			depth++
			current = t.Name.Local
			if t.Name.Local == "explicitMember" || t.Name.Local == "typedMember" {
				ctx.dims++
			}
		case xml.EndElement:
			depth--
			current = ""
		case xml.CharData:
			s := strings.TrimSpace(string(t))
			if s == "" {
				continue
			}
			switch current {
			case "instant":
				ctx.instant = s
			case "startDate":
				ctx.start = s
			case "endDate":
				ctx.end = s
			}
		}
	}
	return ctx, nil
}

func collectText(dec *xml.Decoder, sb *strings.Builder) error {
	depth := 1
	for depth > 0 {
		tok, err := dec.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			depth++
		case xml.EndElement:
			depth--
		case xml.CharData:
			sb.Write(t)
		}
	}
	return nil
}

func sortAccounts(a []Account, order map[string]int) {
	// insertion sort keeps it dependency-free and lists are tiny (<=~22 rows)
	for i := 1; i < len(a); i++ {
		for j := i; j > 0 && less(a[j], a[j-1], order); j-- {
			a[j], a[j-1] = a[j-1], a[j]
		}
	}
}

func less(x, y Account, order map[string]int) bool {
	if order[x.Concept] != order[y.Concept] {
		return order[x.Concept] < order[y.Concept]
	}
	return x.Context < y.Context
}

var deiSet = toSet(deiFields)

func toSet(ss []string) map[string]bool {
	m := make(map[string]bool, len(ss))
	for _, s := range ss {
		m[s] = true
	}
	return m
}
